### ISSUE TITLE
Double hash password at add user

### ISSUE THREAD

**Issue by jankristanto** [hiraq/Cloggy#19]
Double hash password at add user. in user model and users controller. 
I have been patching in my fork :)

**Comment by hiraq** [comment]
tracking repo: (steps)

https://help.github.com/articles/fork-a-repo (fork repo)
https://help.github.com/articles/using-pull-requests (pull request)

**Comment by hiraq** [comment]
fixed: patch -> https://github.com/hiraq/Cloggy/tree/v0.5.4.4
