### ISSUE TITLE
Can not setup permission

### ISSUE THREAD

**Issue by golden-illusion** [hiraq/Cloggy#20]
I created a new role. when i setup permissions, it always returns error: "This role and permission has been exists"

**Comment by hiraq** [comment]
Hello,

Thank you for your bug report :+1: , well, i will try to check and fix this bug

**Comment by hiraq** [comment]
Hi Hieu Dang,

Can you tell me more spesific about this issue? I have check this issue, and all role operation running perfectly in my environment

**Comment by golden-illusion** [comment]
ok,
1. I create a role, say 'mob'
2. I set up a new permission: role name: mob; permission type: module; object: myModule; permission: deny;
3. error appears : "This role and permission has been exists".

I try to check again "permission manage" for a newly created one, but nothing there!
thanks for your support! :+1:

**Comment by hiraq** [comment]
oh, okay, i'm get it now, i'll try fix this issue now
